[theme]
base = "light"

[server]
runOnSave = true

[pages]
hideSidebarNav = false

[[pages]]
path = "chat.py"
name = "Chatbot"
icon = "ğŸ’¬"

[[pages]]
path = "admin_panel.py"
name = " "  # blank name hides it from sidebar
icon = "ğŸ”"
